# Generated by Django 3.0.6 on 2020-06-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Teacher', 'Teacher'), ('Student', 'Student')], default='Student', max_length=20),
        ),
    ]
