# Generated by Django 3.0.6 on 2020-06-23 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200623_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 6, 23, 12, 15, 59, 757046, tzinfo=utc)),
        ),
    ]
