# Generated by Django 3.0.6 on 2020-06-23 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20200623_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
